### ISSUE TITLE
 NameError: name 'LOG_DIR' is not defined

### ISSUE THREAD

**Issue by packmad** [Ghirensics/ghiro-docker#2]
With `docker-compose up` I got the following error:

```

Building wheels for collected packages: Pillow, chardet, pymongo, python-magic, nudepy, imagehash, PyWavelets
  Running setup.py bdist_wheel for Pillow: started
  Running setup.py bdist_wheel for Pillow: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/88/2d/ce/3ff4ae4e2b8600d1bde1cbde5dfcc6d8770222c38348fe9139
  Running setup.py bdist_wheel for chardet: started
  Running setup.py bdist_wheel for chardet: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/28/8c/bf/a69199bd4901d84e13362f95a9ea7bc9a691fed2d655a90bc4
  Running setup.py bdist_wheel for pymongo: started
  Running setup.py bdist_wheel for pymongo: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/a6/d7/ea/bd149d9e2fd0f9ab21959b63c250ef509e4e38cc6258f6a07d
  Running setup.py bdist_wheel for python-magic: started
  Running setup.py bdist_wheel for python-magic: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/65/ab/71/40c6c38a050ce64fcbda7e3e8ee3096d5a6302ad4dab28ba8c
  Running setup.py bdist_wheel for nudepy: started
  Running setup.py bdist_wheel for nudepy: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/81/e0/99/a5bfc4df141bfcc6db890aea7bdb1c0481e4394eb7d3a4a90a
  Running setup.py bdist_wheel for imagehash: started
  Running setup.py bdist_wheel for imagehash: finished with status 'done'
  Stored in directory: /root/.cache/pip/wheels/73/55/33/c9e4b4d6034ae53e4df44b0de84b5037b8a485aac7dde3761f
  Running setup.py bdist_wheel for PyWavelets: started
  Running setup.py bdist_wheel for PyWavelets: finished with status 'error'
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-96xKZp/PyWavelets/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpv_e7jrpip-wheel- --python-tag cp27:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-96xKZp/PyWavelets/setup.py", line 224, in <module>
      setup_package()
    File "/tmp/pip-build-96xKZp/PyWavelets/setup.py", line 210, in setup_package
      from numpy.distutils.core import setup
  ImportError: No module named numpy.distutils.core

  ----------------------------------------
  Failed building wheel for PyWavelets
  Running setup.py clean for PyWavelets
Successfully built Pillow chardet pymongo python-magic nudepy imagehash
Failed to build PyWavelets
Installing collected packages: Django, Pillow, chardet, pdfkit, pymongo, six, python-dateutil, python-magic, requests, nudepy, numpy, scipy, PyWavelets, imagehash
  Running setup.py install for PyWavelets: started
    Running setup.py install for PyWavelets: finished with status 'done'
Successfully installed Django-1.9.7 Pillow-3.2.0 PyWavelets-0.4.0 chardet-2.3.0 imagehash-3.0 nudepy-0.2 numpy-1.11.1 pdfkit-0.5.0 pymongo-3.2.2 python-dateutil-2.5.3 python-magic-0.4.11 requests-2.10.0 scipy-0.18.1 six-1.10.0
You are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
 ---> 49e6328d8616
Removing intermediate container 6d413d93d2c2
Step 22 : ADD local_settings.py /var/www/ghiro/ghiro/local_settings.py
 ---> 2de571c0b0dd
Removing intermediate container 27896e5906d7
Step 23 : RUN cd /var/www/ghiro && python manage.py syncdb --noinput
 ---> Running in 39ce2c352c01
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/ghiro/ghiro/settings.py", line 143, in <module>
    if not os.path.exists(LOG_DIR):
NameError: name 'LOG_DIR' is not defined
ERROR: Service 'ghiro' failed to build: The command '/bin/sh -c cd /var/www/ghiro && python manage.py syncdb --noinput' returned a non-zero code: 1

```

**Comment by jekil** [comment]
The ghiro docker is still under development and is not meant for public use, unless you want to help creating it ;)

**Comment by pjebs** [comment]
@six110  Did you manage to get it working? I'm having the same problem myself. I think it maybe because the Dockerfile makes no mention of installing MongoDB but it's definitely required.
