### ISSUE TITLE
Docker build problems

### ISSUE THREAD

**Issue by pjebs** [Ghirensics/ghiro-docker#3]
@jekil I tried to build the docker image using:
`docker build -t ghiro .`

The build process failed due to this situation:
Can you please tell me how I can fix it. It is urgent. Thank you in advance.

```
Step 22 : RUN cd /var/www/ghiro && python manage.py syncdb --noinput
 ---> Running in ebf4105e493c
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 302, in execute
    settings.INSTALLED_APPS
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 55, in __getattr__
    self._setup(name)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/local/lib/python2.7/dist-packages/django/conf/__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/var/www/ghiro/ghiro/settings.py", line 143, in <module>
    if not os.path.exists(LOG_DIR):
NameError: name 'LOG_DIR' is not defined
The command '/bin/sh -c cd /var/www/ghiro && python manage.py syncdb --noinput' returned a non-zero code: 1
```

**Comment by pjebs** [comment]
is it because `syncdb` is deprecated? or because the `Dockerfile` is for an older version of ghiro?

**Comment by pjebs** [comment]
@jekil I would like to help fix up the Dockerfile and make the update available to all.
I don't know python but the error is python related. It would be great if you can help me solve the python related issues.
